apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: greeting-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greeting-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50